export const generosDisponibles = [
    { id: 1, name: "Fantasía" },
    { id: 2, name: "Drama" },
    { id: 3, name: "Infantiles" },
    { id: 4, name: "Romance" },
    { id: 5, name: "Acción" },
    { id: 6, name: "Ciencia ficción" },
    { id: 7, name: "Deportes" },
    { id: 8, name: "Mecha" },
    { id: 9, name: "Magia" },
    { id: 10, name: "Superhéroes" },
    { id: 11, name: "Terror" },
    { id: 12, name: "Misterio" },
    { id: 13, name: "Psicológico" },
    { id: 14, name: "Thriller" },
    { id: 15, name: "Comedia" },
  ];